### ISSUE TITLE
Enable to define custom table id names

### ISSUE THREAD

**Issue by dreinon** [Dashibase/dashibase#21]
**Is your feature request related to a problem?
Now, the default id name "table.id" is used, but one can have different id names.

**Describe the solution you'd like**
An input when creating a page that lets you customize the id name of the table.

**Describe alternatives you've considered**
None

![image](https://user-images.githubusercontent.com/67071425/167679147-2bc4a0a1-48d0-4ffe-8f41-0cd8236834e4.png)

**Comment by alfredlua** [comment]
Hey @dreinon, thanks for raising this. 

We just shipped [an update](https://dashibase.com/changelog) that lets you pick the id column of the table. Let us know if this works for you? 

![image](https://user-images.githubusercontent.com/4110257/171881666-eadf6f40-8041-45c4-a1ab-d1033c03e07f.png)

Please feel free to tell us if you have more suggestions or feedback. :)

**Comment by greentfrapp** [comment]
With the open-source self-hosted option, this can also be specified in the config file via https://github.com/Dashibase/dashibase/blob/aa25f51c6682666cda29372dc125bb3527fa55fa/src/utils/config.ts#L25

Closing this for now but feel free to re-open or create a new issue for follow up.
