### ISSUE TITLE
Url prompted in Preview mode is wrong

### ISSUE THREAD

**Issue by zernonia** [Dashibase/dashibase#52]
**Describe the bug**

**To Reproduce**
1. Go to [Preview](https://app.dashibase.com/preview/afb7608d-f10e-44ae-b033-c9d125b8aae3/login)
2. The prompt on lower right is not showing the correct "APP URL" 

**Expected behavior**
show `https://madewithsupabase.app.dashibase.com`

**Screenshots**
![image](https://user-images.githubusercontent.com/59365435/176133084-2635d7e0-041d-4222-afb3-57ebefc69736.png)

**Desktop (please complete the following information):**
 - OS: macos
 - Browser Chrome

**Comment by greentfrapp** [comment]
Good catch! Just fixed
